name: dl_test
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - torchaudio>=2.0.0
  - pytorch-cuda=12.4
  
  # 컴퓨터 비전
  - opencv>=4.8.0
  - pillow>=9.5.0
  - scikit-image>=0.20.0
  
  # 수치 계산
  - numpy>=1.24.0
  - scipy>=1.10.0
  - scikit-learn>=1.3.0
  
  # 시각화
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  
  # 유틸리티
  - tqdm>=4.65.0
  - jupyter>=1.0.0
  
  # pip 전용 패키지
  - pip
  - pip:
    - PyQt5>=5.15.0
    - pathlib2>=2.3.7
    - pytest>=7.4.0
